In [54]:
# Numpy

# C언어로 개발된 파이썬에서 과학적 계산을 위한 핵심 라이브러리. 다차원 배열 객체와 배열과 함께 작동하는 도구들을 제공한다. 하지만 고수준의 데이터 분석기능을 제공하지는 않기 때문에 Numpy 배열과 함께 Pandas와 같은 도구를 함께 사용한다. 

In [55]:
import numpy as np

In [56]:
arr = np.array([1,2,3,4])
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [57]:
# zeros, ones, empty를 사용해서 배열을 생성한다. 
car = np.zeros((3,3))
print(car)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [58]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [59]:
np.empty((4,4))

array([[1.69526176e-316, 0.00000000e+000, 6.92370208e-310,
        6.92372621e-310],
       [6.92372612e-310, 6.92372612e-310, 6.92372563e-310,
        6.92372560e-310],
       [6.92370200e-310, 3.21142670e-322, 1.65197924e-316,
        6.92372662e-310],
       [6.92370200e-310, 6.92370202e-310, 6.92370200e-310,
        6.92370200e-310]])

In [60]:
# 특정 범위의 변수를 생성할 때 arange()를 사용한다. 
print(np.arange(10))
print(np.arange(1,10))
print(np.arange(1,10,2))

[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


In [61]:
# ndarray 배열의 모양, 차수, 데이터 타입 확인해보기 
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [62]:
# 차원의 확인
arr.ndim

2

In [63]:
# 데이터의 모양을 확인하는 방법
arr.shape

(2, 3)

In [64]:
# 데이터 타입의 확인 
print(type(arr))
print(arr.dtype)

<class 'numpy.ndarray'>
int64


In [65]:
# ndarray 배열의 타입 변환
arr_int = np.array([1,2,3,4])
print(arr_int.dtype)
arr_float = arr_int.astype(np.float64)
print(arr_float.dtype)

int64
float64


In [66]:
arr_str = np.array(['1','2','3','4'])
print(arr_str.dtype)
arr_int = arr_str.astype(np.int64)
print(arr_int.dtype)

<U1
int64


In [67]:
# 배열의 연산
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]


In [68]:
print(np.add(arr1, arr2))
print(np.multiply(arr1, arr2))

[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]


In [69]:
#ndarray 배열 슬라이싱 하기
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

In [70]:
arr_1 = arr[:2,1:3]
print(arr_1)

[[2 3]
 [5 6]]


In [71]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr[0,2]

3

In [72]:
arr = np.array([[1,2,3],[4,5,6]])
idx = arr > 3
print(idx)

[[False False False]
 [ True  True  True]]


In [73]:
arr[idx]

array([4, 5, 6])

In [74]:
redwine = np.loadtxt(fname='winequality-red.csv', delimiter=';', skiprows=1)

FileNotFoundError: ignored

In [ ]:
print(redwine)

In [ ]:
# 기초 통계 함수 
# sum   합계
# mean  평균
# std   표준 편차
# var   분산 (std의 제곱)
# min   최소값
# max   최대값

print(redwine.sum())
print(redwine.sum(axis=0))
print(redwine.mean(axis=0))

In [ ]:
print(redwine[:,0].mean())

In [ ]:
print(redwine.max(axis=0))
print(redwine.min(axis=0))